[package]
name = "semaphore_aggregation"
version = "0.1.0"
edition = "2021"
authors = ["DoHoonKim8"]
description = "Halo2 verifier for aggregated Plonky2 Semaphore proof"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2={ path = "../../plonky2/plonky2" }
anyhow = "1.0.56"   
lazy_static = "1.4.0"
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v0.3.0" }
halo2wrong_maingate = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", package = "maingate", tag = "v2024_01_31" }
# halo2_solidity_verifier = {git="https://github.com/privacy-scaling-explorations/halo2-solidity-verifier.git", tag = "v2024_01_31", features=["evm"]}
halo2_solidity_verifier = {path="../halo2-solidity-verifier", features=["evm"]}
itertools = "0.11"
rand = "0.8"
subtle = "2.4"
num-integer = "0.1"
num-traits = "0.2"
num-bigint = { version = "0.4", features = ["rand"] }
colored = "2.0.0"
rayon = "1.9.0"
hex = "0.4.3"
derive_more = "0.99.17"
num = { version = "0.4", default-features = false, features = ["rand"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
log = "0.4.14"
env_logger = "0.10.0"